# Generated by Django 4.1.10 on 2023-10-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authap', '0004_alter_customuser_is_active_userextralogindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextralogindata',
            name='token_generation_time',
            field=models.DateTimeField(),
        ),
    ]
