# Generated by Django 4.1.10 on 2023-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
