# Generated by Django 4.1.10 on 2023-08-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_useraccount_gender_alter_useraccount_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogindata',
            name='hash_algorithm_id',
        ),
        migrations.RemoveField(
            model_name='userlogindata',
            name='password_salt',
        ),
        migrations.DeleteModel(
            name='HashingAlgo',
        ),
    ]
