# Generated by Django 4.1.10 on 2023-08-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_userlogindata_hash_algorithm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_id',
        ),
    ]
