# Generated by Django 4.1.10 on 2023-08-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_useraccount_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogindata',
            name='login_name',
        ),
    ]
