# Generated by Django 4.1.10 on 2023-08-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_userlogindata_login_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='userlogindata',
            name='email_validation_status',
            field=models.BooleanField(),
        ),
    ]
