# Generated by Django 4.1.10 on 2023-08-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_delete_totaluser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidationstatus',
            name='email_validation_status',
            field=models.BooleanField(),
        ),
    ]
