# Generated by Django 4.1.10 on 2023-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_userlogindata_email_validation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogindata',
            name='email_validation_status',
        ),
        migrations.AddField(
            model_name='userlogindata',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
    ]
