# Generated by Django 4.1.10 on 2023-08-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_remove_userlogindata_email_validation_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogInData',
        ),
    ]
